
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "DEALS_KV"
id = "dfb0374956e1410bbd0f6e8d1ac520e3"

pages_build_output_dir = "public"

pages_build_output_dir = "public"
